theme = "kanagawa-dragon-custom"

[editor]
clipboard-provider = "termcode"
auto-format = true
true-color = true
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.auto-save]
focus-lost = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "file-type", "position", "total-line-numbers", "position-percentage"]

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true

[keys.normal.space]
l = ":reload-all"
q = ":buffer-close"
