return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile" },
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "typescript",
      "tsx",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "markdown",
      "markdown_inline",
      "bash",
      "lua",
      "luadoc",
      "vim",
      "vimdoc",
      "diff",
      "git_config",
      "gitcommit",
      "gitignore",
      "git_rebase",
      "yaml",
      "toml",
      "regex",
      "xml",
      "html",
      "css",
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
